<?php
// fichier de langues en anglais

//general
define("_YES","Yes");
define("_NO","No");
define("_SUPPRIMER","Are you sure you want to delete?");
define("_ANNULER","Cancel");
define("_CONFIRM","Confirm");
define("_ERREUR","Requested page does not exist");

//header
define("_FAQH","FAQ");
define("_ACCUEIL","Home");
define("_MON_PROFIL","My profil");
define("_DECONNEXION","Log out");
define("_CONNEXION","Log in");
define("_RES","Results");

//mon profil
define("_NOM_PRENOM","Full name");
define("_ADRESSE_EMAIL","Email adress");
define("_NUMERO","Phone number");
define("_MODIFIER","Modify");
define("_PROFIL","My profile");

//footer
define("_NOUS_CONTACTER","Contact us");
define("_CGU","Terms");
define("_MENTIONS_LEGALES","Legal notice");
define("_PAGE_CGU","Terms");

//accueil admin/gestionnaire
define("_QSN","Who are we ?");
define("_ALERTE","ALERT");
define("_CAPT_TEMP","Temperature alert");
define("_CAPT_CARD","Heartbeat alert");
define("_CAPT_SON","Sound alert");
define("_GERER_UTILIS","MANAGE USERS");
define("_GES_CAPT","MANAGE SENSORS");
define("_RES_CAND","RESULTS OF CANDIDATES");
define("_GES_ACTI","MANAGE ACTUATORS");
define("_MOD_FIXE","MODIFY BACKOFFICE");
define("_FAQ","MANAGE THE FAQ");

//actionneur
define("_ACT","Actuators page");
define("_CAPT","Sensors page");
define("_ADD_CAPT","Add a sensor");
define("_ADD_ACT","Add an actuator");
define("_ID","ID");
define("_TYPE","Type");
define("_ACTION","Action");
define("_ACT_LUM","Illuminated actuator");
define("_ACT_SON",'Sound actuator');
define("_CAPT_NB","Sensor n°");
define("_ACTI_NB","Actuators n°");
define("_DERN_MODIF","Last modification on");
define("_PAR","by");
define("_TEMPS","Time (minute)");
define("_FREQ_EMISSION","Transmission frequency :");
define("_EMIS_ALEATOIRE","Random transmission");
define("_EMIS_RYTHME","Rythmic transmission");
define("_LUM","Illuminated");
define("_SON","Sound");
define("_SUP_CAPT","Delete a sensor");
define("_SUP_ACTI","Delete an actuator");
define("_MODIF_ACT","Modification of actuators");
define("_MODIF_CAPT","Modification of sensors");

//backoffice
define("_MODIF_CGU","Modify the terms");
define("_MODIF_MENTION","Modify the legal notice");
define("_MODIF_FIXE","Modify the backoffice");
define("_MODIF_TEL","Modify the phone number");
define("_MODIF_QSN","Modifier the Who are we ?");
define("_MODIF_MAIL","Modify the email adress");
define("_DONNE_MODIF","What data do you want to change?");

//faq
define("_ADD_QUESTION","Add a question");
define("_MODIF_QUESTION","Modify a question");
define("_SUP_QUESTION","Delete a question");
define("_SAISIR_QUESTION","Enter a question");
define("_SAISIR_REPONSE","Enter an answer");
define("_MOD_QUESTION","Please change the question");
define("_MOD_REPONSE","Please change the answer");
define("_QUEST","Question");
define("_REP","Answer");

//profil
define("_NEW_EMAIL","New email adress");
define("_MOD_MDP","Modify the password");
define("_ANC_MDP","Old password");
define("_NEW_MDP","New password");
define("_CONF_MDP","Confirm the new password");
define("_NEW_TEL","New phone number");
define("_TEL","Phone number");

//resultat
define("_MOY_UTILI","The average of all users is ");
define("_NOM","Last name");
define("_PRENOM","First name");
define("_DONNE_UTILI","User data");
define("_RESULTAT","Result");
define("_DATE","Date");
define("_VOS_RES","Your result");
define("_VALEUR","Value");
define("_UNITE","Unit");

//user
define("_ADD_USER","Add user");
define("_SUP_USER","Delete user");
define("_MOD_USER","Modify user");
define("_GESTIONNAIRE","Manager");
define("_ADMINISTRATEUR","Administrator");
define("_CANDIDAT","Candidate");
define("_DATE_NAISSANCE","Date of birth");
define("_TAILLE","Size");
define("_POIDS","Weight");
define("_AUTORISATION","You don't have the authorization");
define("_USER","User");

//deconnexion
define("_QUITTE","You have been correctly disconnected");

//authentification
define("_PAGE_AUTHENTIFICATION","Authentication page");
define("_IDENTIF","Identification");
define("_NOM_UTILISA","Login :");
define("_MDP","Password :");
define("_MDP_OUBLIE","Forgotten password?");

//alerte
define("_PAGE_ALERT_TEMP","Temperature alert");
define("_PAGE_ALERT_SON","Sound alert");
define("_PAGE_ALERT_CARD","Heartbeat alert");
define("_CAPTEUR","Sensor n°");
define("_GRAPH1","Graph 1");
define("_GRAPH2","Graph 2");
define("_DONNEES_CAPT","Sensor data");
define("_MIN","Minimum : ");
define("_MAX","Maximum : ");
define("_MOY","Average : ");
define("_INTERVALLE","Adapted interval : ");

//changements
define("_MODIFIER_MDP_PERSONNEL","Modifier le mot de passe");
define("_NOUVEAUMDP","Nouveau mot de passe :");
define("_CMDP","Confirmer mot de passe :");
