<?php
// fichier de langues en français

//general
define("_YES","Oui");
define("_NO","Non");
define("_SUPPRIMER","Etes-vous sur de vouloir supprimer ?");
define("_ANNULER","Annuler");
define("_CONFIRM","Confirmer");
define("_ERREUR","Page demandée inexistante");

//header
define("_FAQH","FAQ");
define("_ACCUEIL","Accueil");
define("_MON_PROFIL","Mon profil");
define("_DECONNEXION","Deconnexion");
define("_CONNEXION","Connexion");
define("_RES","Résultats");

//mon profil
define("_NOM_PRENOM","Nom Prénom");
define("_ADRESSE_EMAIL","Adresse mail");
define("_NUMERO","Numéro de téléphone");
define("_MODIFIER","Modifier");
define("_PROFIL","Mon Profil");

//footer
define("_NOUS_CONTACTER","Nous contacter");
define("_CGU","Conditions générales d'utilisation");
define("_MENTIONS_LEGALES","Mentions légales");
define("_PAGE_CGU","CGU");

//accueil admin/gestionnaire
define("_QSN","Qui sommes-nous ?");
define("_ALERTE","ALERTE");
define("_CAPT_TEMP","Alerte capteur température");
define("_CAPT_CARD","Alerte capteur rythme cardiaque");
define("_CAPT_SON","Alerte capteur sonore");
define("_GERER_UTILIS","GERER LES UTILISATEURS");
define("_GES_CAPT","GESTION DES CAPTEURS");
define("_RES_CAND","RESULTATS DES CANDIDATS");
define("_GES_ACTI","GESTION DES ACTIONNEURS");
define("_MOD_FIXE","MODIFIER LES DONNEES FIXES");
define("_FAQ","GERER LA FAQ");

//actionneur
define("_ACT","Page des actionneurs");
define("_CAPT","Page des capteurs");
define("_ADD_CAPT","Ajouter un capteur");
define("_ADD_ACT","Ajouter un actionneur");
define("_ID","ID");
define("_TYPE","Type");
define("_ACTION","Action");
define("_ACT_LUM","Actionneur lumineux");
define("_ACT_SON",'Actionneur sonore');
define("_CAPT_NB","Capteur n°");
define("_ACTI_NB","Actionneur n°");
define("_DERN_MODIF","Derniere modification le");
define("_PAR","par");
define("_TEMPS","Temps (minute)");
define("_FREQ_EMISSION","Fréquence d'émission :");
define("_EMIS_ALEATOIRE","Emission aléatoire");
define("_EMIS_RYTHME","Emission rythmée");
define("_LUM","Lumineux");
define("_SON","Sonore");
define("_SUP_CAPT","Supprimer un capteur");
define("_SUP_ACTI","Supprimer un actionneur");
define("_MODIF_ACT","Modification des actionneurs");
define("_MODIF_CAPT","Modification des capteurs");

//backoffice
define("_MODIF_CGU","Modifier les conditions générales d'utilisation");
define("_MODIF_MENTION","Modifier les mentions légales");
define("_MODIF_FIXE","Modifier les données fixes");
define("_MODIF_TEL","Modifier le numéro de téléphone");
define("_MODIF_QSN","Modifier Qui sommes-nous ?");
define("_DONNE_MODIF","Quelles données souhaitez-vous modifier ?");

//faq
define("_ADD_QUESTION","Ajouter une question");
define("_MODIF_QUESTION","Modifier une question");
define("_SUP_QUESTION","Supprimer une question");
define("_SAISIR_QUESTION","Saisir une question");
define("_SAISIR_REPONSE","Saisir une reponse");
define("_MOD_QUESTION","Veuillez modifier la question");
define("_MOD_REPONSE","Veuillez modifier la reponse");
define("_QUEST","Question");
define("_REP","Reponse");

//profil
define("_NEW_EMAIL","Nouvelle adresse mail");
define("_MOD_MDP","Modifier le mot de passe");
define("_ANC_MDP","Ancien mot de passe");
define("_NEW_MDP","Nouveau mot de passe");
define("_CONF_MDP","Confirmer votre nouveau mot de passe");
define("_NEW_TEL","Nouveau numéro de téléphone");
define("_TEL","Numéro de téléphone");

//resultat
define("_MOY_UTILI","La moyenne de tous les utilisateurs est de ");
define("_NOM","Nom");
define("_PRENOM","Prenom");
define("_DONNE_UTILI","Données des utilisateurs");
define("_RESULTAT","Résultat");
define("_DATE","Date");
define("_VOS_RES","Vos résultats");
define("_VALEUR","Valeur");
define("_UNITE","Unité");

//user
define("_ADD_USER","Ajouter un utilisateur");
define("_SUP_USER","Supprimer un utilisateur");
define("_MOD_USER","Modifier un utilisateur");
define("_GESTIONNAIRE","Gestionnaire");
define("_ADMINISTRATEUR","Administrateur");
define("_CANDIDAT","Candidat");
define("_DATE_NAISSANCE","Date de naissance");
define("_TAILLE","Taille");
define("_POIDS","Poids");
define("_AUTORISATION","Vous n'avez pas l'autorisation");
define("_USER","Utilisateur");

//deconnexion
define("_QUITTE","Vous avez été correctement déconnecté");

//authentification
define("_PAGE_AUTHENTIFICATION","Page d'authentification");
define("_IDENTIF","Identification");
define("_NOM_UTILISA","Nom d'utilisateur :");
define("_MDP","Mot de passe :");
define("_MDP_OUBLIE","Mot de passe oublié?");

//alerte
define("_PAGE_ALERT_TEMP","Alerte température");
define("_PAGE_ALERT_SON","Alerte capteur sonore");
define("_PAGE_ALERT_CARD","Alerte capteur cardiaque");
define("_CAPTEUR","Capteur n°");
define("_GRAPH1","Graphique 1");
define("_GRAPH2","Graphique 2");
define("_DONNEES_CAPT","Données capteurs");
define("_MIN","Minimum : ");
define("_MAX","Maximum : ");
define("_MOY","Moyenne : ");
define("_INTERVALLE","Intervalle adapté : ");

//changements
define("_MODIFIER_MDP_PERSONNEL","Modify password");
define("_NOUVEAUMDP","New password :");
define("_CMDP","Confirm password :");
