<?php
// fichier de langues en français

//header
define("_FAQH","FAQ");
define("_ACCUEIL","Accueil");
define("_MON_PROFIL","Mon profil");
define("_DECONNEXION","Deconnexion");
define("_CONNEXION","Connexion");

//mon profil
define("_NOM_PRENOM","Nom Prénom");
define("_ADRESSE_EMAIL","Adresse mail");
define("_NUMERO","Numéro de téléphone");
define("_MODIFIER","Modifier");
define("_PROFIL","Mon Profil");

//footer
define("_NOUS_CONTACTER","Nous contacter");
define("_CGU","Conditions générales d'utilisation");
define("_MENTIONS_LEGALES","Mentions légales");

//accueil admin
define("_ALERTE","Alerte");
define("_CAPT_TEMP","Alerte capteur température");
define("_CAPT_CARD","Alerte capteur rythme cardiaque");
define("_CAPT_SON","Alerte capteur sonore");
define("_GESTION","Gestion des droits d'accès");
define("_CS_CANDIDAT","Créer/supprimer un compte candidat");
define("_CS_GESTION","Créer/supprimer un compte gestionnaire");
define("_MODIFIER_MDP","Modifier un mot de passe");
define("_GERER_CAPTEUR","Gérer les capteurs");
define("_MOD_CAPT","Modifier les seuils des capteurs");
define("_AJ_CAPT","Ajouter un capteur");
define("_ENL_CAPT","Enlever un capteur");
define("_DONNEES_CANDIDATS","Données des candidats");
define("_GERER_ACTI","Gérer les actionneurs");
define("_MOD_ACTI","Modifier les seuils des actionneurs");
define("_AJ_ACTI","Ajouter un Actionneur");
define("_ENL_ACTI","Enlever un Actionneur");
define("_FAQ","Gérer la page FAQ");

//deconnexion
define("_LOGOUT","Déconnexion");
define("_QUITTE","Vous avez été correctement déconnecté");

//authentification
define("_PAGE_AUTHENTIFICATION","Page d'authentification");
define("_IDENTIF","Identification");
define("_NOM_UTILISA","Nom d'utilisateur :");
define("_MDP","Mot de passe :");
define("_MDP_OUBLIE","Mot de passe oublié?");
define("_SOUVENIR","Se souvenir de mon mot de passe");

//cgu
define("_PAGE_CGU","CGU");

//mentions legales
define("_PAGE_MENTION","Mentions légales");

//nous contacter
define("_PAGE_CONTACT","Nous contacter");

//alerte temperature
//alerte sonore
//alerte cardiaque
define("_PAGE_ALERT_TEMP","Alerte température");
define("_PAGE_ALERT_SON","Alerte capteur sonore");
define("_PAGE_ALERT_CARD","Alerte capteur cardiaque");
define("_CAPTEUR","Capteur n°");
define("_GRAPH1","Graphique 1");
define("_GRAPH2","Graphique 2");
define("_DONNEES_CAPT","Données capteurs");
define("_MIN","Minimum : ");
define("_MAX","Maximum : ");
define("_MOY","Moyenne : ");
define("_INTERVALLE","Intervalle adapté : ");

//gestion acces candidat et gestionnaire
define("_CREER_CANDIDAT","Créer un compte candidat");
define("_CREER_GESTIONNAIRE","Créer un compte gestionnaire");
define("_SUP_CANDIDAT","Supprimer un compte candidat");
define("_SUP_GESTIONNAIRE","Supprimer un compte gestionnaire");
define("_SAISIR_MDP","Saisir votre mot de passe pour valider");
define("_SAISIR_CANDIDAT","Saisir l'adresse mail du candidat");
define("_SAISIR_GESTIONNAIRE","Saisir l'adresse mail du gestionnaire");
define("_SAISIR_CAND","Saisir le nom d'utilisateur du nouveau candidat");
define("_SAISIR_GEST","Saisir le nom d'utilisateur du nouveau gestionnaire");
define("_SUP_CAND","Saisir le nom d'utilisateur du candidat à supprimer");
define("_SUP_GEST","Saisir le nom d'utilisateur du gestionnaire à supprimer");

//changements
define("_MODIFIER_MDP_PERSONNEL","Modifier le mot de passe");
define("_NOUVEAUMDP","Nouveau mot de passe :");
define("_CMDP","Confirmer mot de passe :");
?>
